//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedSalaryProcessingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conuass
    {
        public int id { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<int> step { get; set; }
        public Nullable<decimal> consolidated { get; set; }
        public Nullable<decimal> rent { get; set; }
        public Nullable<decimal> hazard { get; set; }
        public Nullable<decimal> eWA { get; set; }
        public Nullable<decimal> con1 { get; set; }
        public Nullable<decimal> con2 { get; set; }
        public Nullable<decimal> bonus { get; set; }
        public Nullable<decimal> applicable { get; set; }
        public Nullable<decimal> responsibilityAllowance { get; set; }
        public Nullable<decimal> pension { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
