//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedSalaryProcessingSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EUIm : DbContext
    {
        public EUIm()
            : base("name=EUIm")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accountant> accountants { get; set; }
        public virtual DbSet<contiss> contisses { get; set; }
        public virtual DbSet<Contractor> Contractors { get; set; }
        public virtual DbSet<Conuass> Conuasses { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<emContiss> emContisses { get; set; }
        public virtual DbSet<emConuass> emConuasses { get; set; }
        public virtual DbSet<emlevel> emlevels { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<emrank> emranks { get; set; }
        public virtual DbSet<emStep> emSteps { get; set; }
        public virtual DbSet<faculty> faculties { get; set; }
        public virtual DbSet<level> levels { get; set; }
        public virtual DbSet<nCONTISS> nCONTISSes { get; set; }
        public virtual DbSet<nCONUASS> nCONUASSes { get; set; }
        public virtual DbSet<payslip> payslips { get; set; }
        public virtual DbSet<rank> ranks { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<salaryContractor> salaryContractors { get; set; }
        public virtual DbSet<step> steps { get; set; }
    }
}
