//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedSalaryProcessingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class nCONUASS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nCONUASS()
        {
            this.emConuasses = new HashSet<emConuass>();
        }
    
        public int id { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<int> step { get; set; }
        public Nullable<decimal> basicSalary { get; set; }
        public Nullable<decimal> hazard { get; set; }
        public Nullable<decimal> EWA { get; set; }
        public Nullable<decimal> responsibilityAllowance { get; set; }
        public Nullable<decimal> pension { get; set; }
        public Nullable<decimal> tax { get; set; }
        public Nullable<decimal> total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emConuass> emConuasses { get; set; }
    }
}
