//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedSalaryProcessingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salary()
        {
            this.payslips = new HashSet<payslip>();
        }
    
        public int id { get; set; }
        public int employeeid { get; set; }
        public Nullable<float> salary1 { get; set; }
        public Nullable<float> EWA { get; set; }
        public Nullable<float> total { get; set; }
        public Nullable<float> OA { get; set; }
        public Nullable<float> HA { get; set; }
        public Nullable<float> RA { get; set; }
        public Nullable<float> HW { get; set; }
        public Nullable<float> bonus { get; set; }
    
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payslip> payslips { get; set; }
    }
}
