//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedSalaryProcessingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class salaryContractor
    {
        public int id { get; set; }
        public int contractorID { get; set; }
        public int hoursWorked { get; set; }
        public float pay { get; set; }
        public Nullable<float> bonus { get; set; }
    
        public virtual Contractor Contractor { get; set; }
    }
}
